### ISSUE TITLE
ポルノコンテンツを検知できない

### ISSUE THREAD

**Issue by s3-odara** [GIZMODO-WOODS/wiki#5]

**Comment by s3-odara** [comment]
Discordの正規表現はデフォルトで大文字小文字を区別しないらしい
https://support.discord.com/hc/en-us/articles/10069840290711-Filter-Messages-Using-Regular-Expressions-Regex-

> Case-insensitive and unicode support flags are on by default for every regex pattern.

**Comment by takpika** [comment]
レポジトリ移動のため
